# Generated by Django 5.1.6 on 2026-03-28 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_document_file_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='accesspermission',
            name='idx_perm_patient',
        ),
        migrations.RemoveIndex(
            model_name='accesspermission',
            name='idx_perm_doctor',
        ),
        migrations.RemoveIndex(
            model_name='accesspermission',
            name='idx_perm_active',
        ),
        migrations.AddField(
            model_name='accesspermission',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accesspermission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('revoked', 'Revoked')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='accesspermission',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accesspermission',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions_granted', to=settings.AUTH_USER_MODEL),
        ),
    ]
