# Generated by Django 5.1.6 on 2026-03-27 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_document_file_hash_document_idx_doc_file_hash'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='document',
            new_name='idx_doc_hash',
            old_name='idx_doc_file_hash',
        ),
    ]
